import streamlit as st
import google.genai as genai
from dotenv import load_dotenv
import os

load_dotenv() 

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

st.set_page_config(page_title="IdeaEvaluator", layout="wide")

# Title and header
st.title("IdeaEvaluator — AI Startup Idea Checker")
st.markdown("---")

# Layout: Tabs para separar a funcionalidade principal das explicações
tab_evaluate, tab_about = st.tabs(["💡 Evaluate Your Idea", "📖 About the Project"])

with tab_about:
    st.header("About IdeaEvaluator")
    left, right = st.columns([1, 1])
    
    with left:
        st.subheader("Why use IdeaEvaluator?")
        st.markdown(
            "- It gives data-backed (via AI) insights into the potential of an early-stage startup idea, even before any product is built.\n"
            "- It offers an **IdeaScore**, an arbitrary but indicative score out of 10 based on AI heuristics.\n"
            "- It quickly highlights the main **Pros** and **Cons** of your concept to help you pivot or validate.\n"
        )

    with right:
        st.subheader("What is the IdeaScore?")
        st.markdown(
            "The **IdeaScore** is a heuristic metric (1 to 10) generated by the AI model analyzing various factors such as:\n"
            "- **Potential market demand:** Is there a clear problem being solved?\n"
            "- **Level of competition:** Is the market too saturated?\n"
            "- **Overall viability:** Does the solution make technical and business sense?\n\n"
            "*Note: This score is a simulated evaluation generated by an LLM and should be used as a starting point for real-world validation, not as a definitive proof of success.*"
        )

with tab_evaluate:
    st.header("Submit and Evaluate")
    st.write(
        "Enter your startup idea below. Our AI will analyze your concept, outline its strengths and weaknesses, "
        "and provide an **IdeaScore** to help you gauge its potential."
    )

    idea_input = st.text_area(
        "Describe your idea (one or two sentences)", 
        height=120, 
        placeholder="e.g., An AI tool that predicts startup success using public data and provides an IdeaScore."
    )

    if st.button("Evaluate Idea", type="primary"):
        if not idea_input.strip():
            st.warning("Please enter an idea to evaluate.")
        elif GEMINI_API_KEY is None:
            st.error("Please configure your Google Gemini API key via environment variable (GEMINI_API_KEY) to run the evaluation.")
        else:
            with st.spinner("Analyzing your idea... This may take a few seconds."):
                try:
                    client = genai.Client(api_key=GEMINI_API_KEY)
                    
                    prompt = (
                        f"You are an expert startup advisor and experienced venture capitalist. "
                        f"Evaluate the following startup idea: '{idea_input}'.\n\n"
                        "Please provide your evaluation structured EXACTLY as follows:\n\n"
                        "### Summary\n"
                        "(Provide a brief summary of whether it is a good idea or a bad idea and why)\n\n"
                        "### Pros & Cons\n"
                        "(List 2-3 bullet points for Pros, and 2-3 bullet points for Cons)\n\n"
                        "### IdeaScore: [Score]/10\n"
                        "(Give an arbitrary score out of 10 based on market viability, followed by a 1-sentence justification for the score.)"
                    )
                    
                    response = client.models.generate_content(
                        model="gemini-2.0-flash",
                        contents=prompt,
                    )
                    
                    evaluation = response.text
                    
                    st.markdown("---")
                    st.subheader("📊 Evaluation Results")
                    
                    with st.container():
                        st.markdown(evaluation)
                        
                    st.success("Analysis complete!")
                    st.info("💡 **Next Steps:** Use these insights to validate your idea with real users. Remember, the IdeaScore is just a guide, execution is what matters!")
                    
                except Exception as e:
                    st.error(f"An error occurred while connecting to the Google Gemini API: {e}")

