import streamlit as st
import google.genai as genai
from dotenv import load_dotenv
import os
import json

load_dotenv() 

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

def generate_mock_evaluation(idea_input):
    """Gera uma avaliação simulada como fallback quando a API está com quota excedida."""
    scores = [7, 8, 7.5, 8.5, 6.5, 7, 8, 7.5]
    idea_hash = sum(ord(c) for c in idea_input) % len(scores)
    score = scores[idea_hash]
    
    pros = [
        "✓ Clear problem-solution fit",
        "✓ Growing market opportunity",
        "✓ Scalable business model"
    ]
    
    cons = [
        "✗ Increasing competition",
        "✗ High customer acquisition cost",
        "✗ Regulatory uncertainties"
    ]
    
    evaluation = f"""### Summary
This is a promising startup concept with good market potential. The idea addresses a real problem and has a reasonable path to profitability. With proper execution and market validation, this could become a viable business.

### Pros & Cons

**Pros:**
- {pros[0]}
- {pros[1]}
- {pros[2]}

**Cons:**
- {cons[0]}
- {cons[1]}
- {cons[2]}

### IdeaScore: {score}/10
The concept shows strong potential with adequate market demand and execution feasibility."""
    
    return evaluation

st.set_page_config(page_title="IdeaEvaluator", layout="wide")

# Title and header
st.title("IdeaEvaluator — AI Startup Idea Checker")
st.markdown("---")

# Layout: Tabs para separar a funcionalidade principal das explicações
tab_evaluate, tab_about = st.tabs(["💡 Evaluate Your Idea", "📖 About the Project"])

with tab_about:
    st.header("About IdeaEvaluator")
    left, right = st.columns([1, 1])
    
    with left:
        st.subheader("Why use IdeaEvaluator?")
        st.markdown(
            "- It gives data-backed (via AI) insights into the potential of an early-stage startup idea, even before any product is built.\n"
            "- It offers an **IdeaScore**, an arbitrary but indicative score out of 10 based on AI heuristics.\n"
            "- It quickly highlights the main **Pros** and **Cons** of your concept to help you pivot or validate.\n"
        )

    with right:
        st.subheader("What is the IdeaScore?")
        st.markdown(
            "The **IdeaScore** is a heuristic metric (1 to 10) generated by the AI model analyzing various factors such as:\n"
            "- **Potential market demand:** Is there a clear problem being solved?\n"
            "- **Level of competition:** Is the market too saturated?\n"
            "- **Overall viability:** Does the solution make technical and business sense?\n\n"
            "*Note: This score is a simulated evaluation generated by an LLM and should be used as a starting point for real-world validation, not as a definitive proof of success.*"
        )

with tab_evaluate:
    st.header("Submit and Evaluate")
    st.write(
        "Enter your startup idea below. Our AI will analyze your concept, outline its strengths and weaknesses, "
        "and provide an **IdeaScore** to help you gauge its potential."
    )

    idea_input = st.text_area(
        "Describe your idea (one or two sentences)", 
        height=120, 
        placeholder="e.g., An AI tool that predicts startup success using public data and provides an IdeaScore."
    )

    if st.button("Evaluate Idea", type="primary"):
        if not idea_input.strip():
            st.warning("Please enter an idea to evaluate.")
        elif GEMINI_API_KEY is None:
            st.error("Please configure your Google Gemini API key via environment variable (GEMINI_API_KEY) to run the evaluation.")
        else:
            with st.spinner("Analyzing your idea... This may take a few seconds."):
                try:
                    client = genai.Client(api_key=GEMINI_API_KEY)
                    
                    prompt = (
                        f"You are an expert startup advisor and experienced venture capitalist. "
                        f"Evaluate the following startup idea: '{idea_input}'.\n\n"
                        "Please provide your evaluation structured EXACTLY as follows:\n\n"
                        "### Summary\n"
                        "(Provide a brief summary of whether it is a good idea or a bad idea and why)\n\n"
                        "### Pros & Cons\n"
                        "(List 2-3 bullet points for Pros, and 2-3 bullet points for Cons)\n\n"
                        "### IdeaScore: [Score]/10\n"
                        "(Give an arbitrary score out of 10 based on market viability, followed by a 1-sentence justification for the score.)"
                    )
                    
                    response = client.models.generate_content(
                        model="gemini-2.0-flash",
                        contents=prompt,
                    )
                    
                    evaluation = response.text
                    
                    st.markdown("---")
                    st.subheader("📊 Evaluation Results")
                    
                    with st.container():
                        st.markdown(evaluation)
                        
                    st.success("Analysis complete!")
                    st.info("💡 **Next Steps:** Use these insights to validate your idea with real users. Remember, the IdeaScore is just a guide, execution is what matters!")
                    
                except Exception as e:
                    error_str = str(e)
                    
                    # Exceded quota handling
                    if "429" in error_str or "RESOURCE_EXHAUSTED" in error_str:
                        st.warning(
                            "⚠️ **API Quota Exceeded** - Your free tier quota has been reached. "
                            "Please upgrade your plan or try again later. "
                            "For now, showing a sample evaluation:"
                        )
                        
                        # Fallback
                        mock_evaluation = generate_mock_evaluation(idea_input)
                        
                        st.markdown("---")
                        st.subheader("📊 Sample Evaluation Results")
                        st.info("💡 **This is a simulated example** - To get real AI-powered insights, please upgrade your Gemini API plan.")
                        
                        with st.container():
                            st.markdown(mock_evaluation)
                    else:
                        st.error(f"An error occurred while connecting to the Google Gemini API: {e}")

